py3: convert dict_keys to list
Addresses error on py3 based setup:

  TypeError: 'dict_keys' object does not support indexing

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>