teuthology/orchestra: open log file in Python3 way
otherwise we could have
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'file' is not defined
```

Fixes: https://tracker.ceph.com/issues/45512
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 9874f7a24c6620e551d3c6e844dc63b9168b0c21)