Pins mock to version 1.0.1
mock was updated on 07/10/15 and this new version introduced an issue we
experience when running tests. The trace we get is:

    teuthology/test/test_ls.py:3: in <module>
        from mock import patch, Mock
    .tox/py27/local/lib/python2.7/site-packages/mock/__init__.py:2: in <module>
        import mock.mock as _mock
    .tox/py27/local/lib/python2.7/site-packages/mock/mock.py:68: in <module>
        from six import wraps
    E   ImportError: cannot import name wraps

Reverting to previous version (mock==1.0.1) fixes the issue.