fog: suggest image names
Improve the error message when the user specifies a missing OS version
for a machine type.

Old error message:

  RuntimeError: Could not find an image for rhel 7.9

New error message:

  RuntimeError: Fog has no cali_rhel_7.9 image.
                Available cali images: ['cali_rhel_8.6', 'cali_rhel_9.0']